### ISSUE TITLE
GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_OUT_OF_RESOURCES PlotInfo(prover=<chiapos.DiskProver object at 0xffffa950a5f0>, po

### ISSUE THREAD

**Issue by liliput629** [foxypool/foxy-gh-farmer#11]
Hello,

I 've using  rock-4c-plus 5.10.110-1-rockchip 

with foxy-gigahores 1.2 and work fine, but the new versions 1.4.2 , 1.6.2 , 1.72, seem that don't run correctly:(logfile:)

2023-11-27T21:30:17.196 foxy_gh_farmer harvester          : INFO     1 plots were eligible for farming a6c9faee5b... Found 0 proofs. Time: 44.29412 s. Total 296 plots
2023-11-27T21:30:17.224 foxy_gh_farmer harvester          : INFO     Saved 302728 bytes of cached data
2023-11-27T21:30:17.496 foxy_gh_farmer harvester          : INFO     1 plots were eligible for farming a6c9faee5b... Found 0 proofs. Time: 0.45258 s. Total 296 plots
2023-11-27T21:30:19.645 foxy_gh_farmer harvester          : ERROR    Exception fetching qualities for /media/chia/WD-14/chia_nft/plot-k32-c1-2023-07-01-20-11-e5d79859712099b0b3f977b3a2f4ce0b328fa7ad3b07639357ea844d76eb89a3.plot: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_OUT_OF_RESOURCES PlotInfo(prover=<chiapos.DiskProver object at 0xffffa950a5f0>, pool_public_key=None, pool_contract_puzzle_hash=<bytes32: f79ef50603bec8f1b49e5cae0c45936c293eb27c320072e73343642f2b7ee7f0>, plot_public_key=<G1Element 9594c169057b937eec67b3a5c57d57ea650f5c46df33b0273043328e26d2c822d4f487bb3c4085736fa27f55098c4770>, file_size=90581981401, time_modified=1688249491.0896242)
2023-11-27T21:30:19.655 foxy_gh_farmer harvester          : INFO     1 plots were eligible for farming a6c9faee5b... Found 0 proofs. Time: 1.47503 s. Total 296 plots
2023-11-27T21:30:26.905 foxy_gh_farmer harvester          : INFO     0 plots were eligible for farming a6c9faee5b... Found 0 proofs. Time: 0.07344 s. Total 296 plots
2023-11-27T21:30:36.878 foxy_gh_farmer harvester          : INFO     1 plots were eligible for farming a6c9faee5b... Found 0 proofs. Time: 0.43295 s. Total 296 plots
^C2023-11-27T21:30:41.538 foxy_g

thanks

**Comment by felixbrucker** [comment]
Hi, can you check whether your gpu is still working in the system? Also can you monitor ram and vram usage on the system while idle and when running foxy-gh-farmer/gigahorse?

**Comment by liliput629** [comment]
Hello 

i don't now how view gpu , is a Mali T860MP4 gpu:

![radxa c plus](https://github.com/foxypool/foxy-gh-farmer/assets/147952491/3d00031c-d0ae-4056-847d-2be0d2e0fb2d)

top with foxy-gh-farmer   :
![top-foxy-gh-farmer](https://github.com/foxypool/foxy-gh-farmer/assets/147952491/89d3d64c-cfe2-4c49-98b4-6a539c3c3092)

top- without foxy-gh-farmer: 
![top-foxy-gh-farmer without](https://github.com/foxypool/foxy-gh-farmer/assets/147952491/c81bd7ce-cdf7-424f-b48b-ce3dd640f583)

**Comment by felixbrucker** [comment]
Yeah, ram is probably shared with the gpu and gets OOM, in that screen its at 145 mb free while foxy-gh-farmer is running and only 582mb free when it is not. It could very well be that the new proof cache in gigahorse 24 and the 2.1.1 chia codebase now require a bit more ram and vram respectively, resulting in oom in your case.
Can you try to get free ram without foxy-gh-farmer running a bit higher, like 1G (so another 400mb freed)?

Another thing as you have cached data in ram as well and swap, this really shouldn't be an issue, it might be the vram reserved part of the ram is too small (or maybe it even has dedicated vram, not sure on that)

Can you run the clinfo command for that gpu? that should probably tell

**Comment by liliput629** [comment]
Clinfo:

radxa@rock-4c-plus:~$ sudo clinfo
arm_release_ver of this libmali is 'r18p0-01rel0', rk_so_ver is '4'.Number of platforms                                                                                                                1
  Platform Name                                   ARM Platform
  Platform Vendor                                 ARM
  Platform Version                                OpenCL 1.2 v1.r18p0-01rel0.5cb5681058e8e07                                                                                 6ff89747c20c32578
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_gl                                                                                 obal_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atom                                                                                 ics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_fp64 cl_khr_int64_base_atomi                                                                                 cs cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_icd cl_khr_egl_image cl_khr_image2d_from                                                                                 _buffer cl_arm_core_id cl_arm_printf cl_arm_thread_limit_hint cl_arm_non_uniform_work_group_                                                                                 size cl_arm_import_memory
  Platform Extensions function suffix             ARM

  Platform Name                                   ARM Platform
Number of devices                                 1
  Device Name                                     Mali-T860
  Device Vendor                                   ARM
  Device Vendor ID                                0x8602000
  Device Version                                  OpenCL 1.2 v1.r18p0-01rel0.5cb5681058e8e07                                                                                 6ff89747c20c32578
  Driver Version                                  1.2
  Device OpenCL C Version                         OpenCL C 1.2 v1.r18p0-01rel0.5cb5681058e8e                                                                                 076ff89747c20c32578
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               4
  Available core IDs                              <printDeviceInfo:31: get CL_DEVICE_COMPUTE                                                                                 _UNITS_BITFIELD_ARM : error -30>
  Max clock frequency                             5MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple (kernel)     4
  Preferred / native vector sizes
    char                                                16 / 16
    short                                                8 / 8
    int                                                  4 / 4
    long                                                 2 / 2
    half                                                 8 / 8        (cl_khr_fp16)
    float                                                4 / 4
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              2080309248 (1.937GiB)
  Error Correction support                        No
  Max memory allocation                           520077312 (496MiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        262144 (256KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   32 bytes
    Pitch alignment for 2D image buffers          16 pixels
    Max 2D image size                             65536x65536 pixels
    Max 3D image size                             65536x65536x65536 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Global
  Local memory size                               32768 (32KiB)
  Max number of constant args                     8
  Max constant buffer size                        65536 (64KiB)
  Max size of kernel argument                     1024
  Queue properties
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Prefer user sync for interop                    No
  Profiling timer resolution                      1000ns
  Execution capabilities
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_gl                                                                                 obal_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atom                                                                                 ics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_fp64 cl_khr_int64_base_atomi                                                                                 cs cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_icd cl_khr_egl_image cl_khr_image2d_from                                                                                 _buffer cl_arm_core_id cl_arm_printf cl_arm_thread_limit_hint cl_arm_non_uniform_work_group_                                                                                 size cl_arm_import_memory

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  ARM Platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [ARM]
  clCreateContext(NULL, ...) [default]            Success [ARM]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 ARM Platform
    Device Name                                   Mali-T860
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 ARM Platform
    Device Name                                   Mali-T860
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 ARM Platform
    Device Name                                   Mali-T860

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.14
  ICD loader Profile                              OpenCL 3.0



When i reboot te compute memory si 1449 freee , i start foxy-farmer and obtain same error:

![top-foxy-gh-farmer without-start](https://github.com/foxypool/foxy-gh-farmer/assets/147952491/5e05a406-ec1f-4b95-a5f9-c0a6ef0bc194)

**Comment by felixbrucker** [comment]
This could just be gigahorse requiring more vram or another issue with gigahorse, to validate its not related to foxy-gh-farmer can you please run gigahorse manually?

First stop foxy-gh-farmer, then run the following commands:
```bash
CHIA_ROOT=~/.foxy-gh-farmer/mainnet ~/.foxy-gh-farmer/bin-cache/2.1.1.giga25/chia-gigahorse-farmer/chia.bin run_daemon
CHIA_ROOT=~/.foxy-gh-farmer/mainnet ~/.foxy-gh-farmer/bin-cache/2.1.1.giga25/chia-gigahorse-farmer/chia.bin start farmer-only harvester
```

Do you see the same behaviour there?

**Comment by liliput629** [comment]
Hello 

i ve launched two line without errors:


radxa@rock-4c-plus:/chia/foxy-gh-farmer$ sudo CHIA_ROOT=/root/.foxy-gh-farmer/mainnet /root/.foxy-gh-farmer/bin-cache/2.1.1.giga25/chia-gigahorse-farmer/chia.bin run_daemon
CHIA_ROOT is set to /root/.foxy-gh-farmer/mainnet
Chia directory /root/.foxy-gh-farmer/mainnet
/root/.foxy-gh-farmer/mainnet already exists, no migration action taken

{"ca_crt": "/root/.foxy-gh-farmer/mainnet/config/ssl/ca/private_ca.crt", "cert": "/root/.foxy-gh-farmer/mainnet/config/ssl/daemon/private_daemon.crt", "key": "/root/.foxy-gh-farmer/mainnet/config/ssl/daemon/private_daemon.key", "message": "cert_path", "success": true}
daemon: already launching
radxa@rock-4c-plus:/chia/foxy-gh-farmer$


radxa@rock-4c-plus:/chia/foxy-gh-farmer$ sudo CHIA_ROOT=/root/.foxy-gh-farmer/mainnet /root/.foxy-gh-farmer/bin-cache/2.1.1.giga25/chia-gigahorse-farmer/chia.bin start farmer-only harvester
chia_farmer: Already running, use `-r` to restart
chia_harvester: Already running, use `-r` to restart
radxa@rock-4c-plus:/chia/foxy-gh-farmer$ sudo CHIA_ROOT=/root/.foxy-gh-farmer/mainnet /root/.foxy-gh-farmer/bin-cache/2.1.1.giga25/chia-gigahorse-farmer/chia.bin start farmer-only harvester -r
chia_farmer: stopped
chia_farmer: started
chia_harvester: stopped
chia_harvester: started
radxa@rock-4c-plus:/chia/foxy-gh-farmer$

**Comment by felixbrucker** [comment]
That means it was already running, please ensure all processes from chia/gigahorse are closed

**Comment by liliput629** [comment]
i ve reboot the device and start two processes  , but i don't see any error: 
![gigahorse](https://github.com/foxypool/foxy-gh-farmer/assets/147952491/8011aa74-cefd-4f13-aee3-295a9384f0bd)

**Comment by felixbrucker** [comment]
Can you verify no such errors as originally reported occur with this? Might need to let it run for a bit to be sure
> 2023-11-27T21:30:19.645 foxy_gh_farmer harvester : ERROR Exception fetching qualities for /media/chia/WD-14/chia_nft/plot-k32-c1-2023-07-01-20-11-e5d79859712099b0b3f977b3a2f4ce0b328fa7ad3b07639357ea844d76eb89a3.plot: GPU recompute failed with: clEnqueueNDRangeKernel() failed for kernel 'kernel0' with CL_OUT_OF_RESOURCES PlotInfo(prover=<chiapos.DiskProver object at 0xffffa950a5f0>, pool_public_key=None, pool_contract_puzzle_hash=<bytes32: f79ef50603bec8f1b49e5cae0c45936c293eb27c320072e73343642f2b7ee7f0>, plot_public_key=<G1Element 9594c169057b937eec67b3a5c57d57ea650f5c46df33b0273043328e26d2c822d4f487bb3c4085736fa27f55098c4770>, file_size=90581981401, time_modified=1688249491.0896242)

**Comment by liliput629** [comment]
Hello , i don't know , if i are doing correctly:
 1. lounch gigahorse damon and it leave running. (chia.bin run_daemo)
 2. launch gigahorser hrverster. (chia.bin start farmer-only harvester)
 3. launch foxy-gh-farmer.

doing this i don't see errors on gigahorse daemon, but i see error on foxy-gh-farmer , 

![gh2](https://github.com/foxypool/foxy-gh-farmer/assets/147952491/4c2786cc-1321-4e0b-930f-a94da63d59ba)

**Comment by felixbrucker** [comment]
Alright yes, you could omit starting foxy-gh-farmer, in that case it will just print the log of the running instance. So it seems like gigahorse changed in a way that won't work on your system anymore, can you report this issue in the gigahorse repo?

**Comment by liliput629** [comment]
Yes , i wll open a issue on gigahorse,

thanks

**Comment by felixbrucker** [comment]
Closing here
